modLoader="javafml"
loaderVersion="[34,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/CurioOfUndying/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.curioofundying]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curioofundying]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curioofundying]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.3-4.0.2.0,)"
    ordering="NONE"
    side="BOTH"